src/learndutch/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import TemplateView
from learndutch.mainapp.views import *
from django.conf.urls.static import static
from learndutch import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'learndutch.views.home', name='home'),
    # url(r'^learndutch/', include('learndutch.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    url(r'^$', PageView.as_view(), kwargs={'slug':'_home'}, name="home"),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page':'/'}),
    url(r'^add-noun/$', CreateNounView.as_view(), name="add-noun"),
    url(r'^add-verb/$', CreateVerbView.as_view(), name="add-verb"),
    url(r'^add-adjective/$', CreateAdjectiveView.as_view(), name="add-adjective"),
    url(r'^add-word/$', CreateWordView.as_view(), name="add-word"),
    url(r'^add-sentence/$', CreateSentenceView.as_view(), name="add-sentence"),
    url(r'^add-tag/$', CreateTagView.as_view(), name="add-tag"),
    url(r'^add-page/$', CreatePageView.as_view(), name='add-page'),
    url(r'^word/(?P<slug>(\w+-?)+)/$', WordView.as_view(), name='search-word'),
    url(r'^word/(?P<slug>(\w+-?)+)/edit/$', UpdateWordView.as_view(), name='update-word'),
    url(r'^words/verbs/$', VerbListView.as_view(), name="verbs"),
    url(r'^words/nouns/$', NounListView.as_view(), name="nouns"),
    url(r'^words/adjectives/$', AdjectiveListView.as_view(), name="adjectives"),
    url(r'^words/prepositions/$', PrepositionListView.as_view(), name="prepositions"),
    url(r'^words/$', WordListView.as_view(), name="words"),
    url(r'^page/(?P<slug>(?=_)(\w+-?)+)/$', HiddenPageView.as_view(), name='hidden-page'),
    url(r'^page/(?P<slug>(\w+-?)+)/$', PageView.as_view(), name='page'),
    url(r'^page/(?P<slug>(\w+-?)+)/edit/$', UpdatePageView.as_view(), name='update-page'),
    url(r'^pages/$', PageListView.as_view(), name='pages'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/learndutch/mainapp/models.py
from django.db import models

WORD_TYPE_NOUN = 1
WORD_TYPE_VERB = 2
WORD_TYPE_ADJECTIVE = 4
WORD_TYPE_PREPOSITION = 5
WORD_TYPE_PLAIN = 99

def lookup_value(choices, key, default='?'):
    for k, v in choices:
        if k == key and v == '/': return ''
        if k == key: return v
    return default

def get_formatted(value, format, ifnone='?'):
    if value:
        return format % value
    else:
        return ifnone

class Word(models.Model):
    WORD_TYPE_CHOICES = (
        (WORD_TYPE_PREPOSITION, "Preposition"),
        (WORD_TYPE_PLAIN, "Plain"),
    )
    word_type = models.IntegerField(blank=True)
    word = models.CharField(max_length=255, unique=True)
    meaning = models.CharField(max_length=255, null=True, blank=True)
    info = models.CharField(max_length=1024, null=True, blank=True)
    image = models.ImageField(upload_to='word-image', null=True, blank=True)
    audio = models.FileField(upload_to='word-sound', null=True, blank=True)
    
    @property
    def is_noun(self):
        return self.word_type == WORD_TYPE_NOUN

    @property
    def is_verb(self):
        return self.word_type == WORD_TYPE_VERB

    @property
    def is_adjective(self):
        return self.word_type == WORD_TYPE_ADJECTIVE
    
    def get_meaning(self):
        return get_formatted(self.meaning, '- %s', '')

    def get_absolute_url(self):
        return '/word/%s/' % self.word

    def get_edit_url(self):
        return self.get_absolute_url() + "edit/"

    def get_word(self):
        return self.word

class Noun(Word):
    DEFINITE_ARTICLE_CHOICES = (
        (1, 'de'),
        (2, 'het'),
        (3, '/'),
    )
    INDEFINITE_ARTICLE_CHOICES = (
        (1, 'een'),
        (2, '/'),
    )
    definite_article = models.IntegerField(null=True, blank=True, choices=DEFINITE_ARTICLE_CHOICES)
    indefinite_article = models.IntegerField(null=True, blank=True, choices=INDEFINITE_ARTICLE_CHOICES)
    plural = models.CharField(max_length=255, null=True, blank=True)
    diminutive = models.CharField(max_length=255, null=True, blank=True)

    @property
    def get_singular(self):
        article = lookup_value(Noun.DEFINITE_ARTICLE_CHOICES, self.definite_article)
        return '%s %s' % (article, self.word)

    @property
    def get_plural(self):
        if self.definite_article == 3:
            return self.plural
        else:
            return get_formatted(self.plural, 'de %s')

    @property
    def get_indefinite_singular(self):
        article = lookup_value(Noun.INDEFINITE_ARTICLE_CHOICES, self.indefinite_article)
        return '%s %s' % (article, self.word)

    @property
    def get_indefinite_plural(self):
        return get_formatted(self.plural, '%s')

    @property
    def get_diminutive(self):
        return get_formatted(self.diminutive, 'het %s')

    def get_word(self):
        return self.get_singular()


class Verb(Word):
    PAST_PERFECT_AUX_CHOICES = (
        (1, 'hebben'),
        (2, 'zijn'),
    )
    present_1st = models.CharField(max_length=255, null=True, blank=True)
    present_2nd = models.CharField(max_length=255, null=True, blank=True)
    present_3rd = models.CharField(max_length=255, null=True, blank=True)
    past_singular = models.CharField(max_length=255, null=True, blank=True)
    past_plural = models.CharField(max_length=255, null=True, blank=True)
    past_perfect_aux = models.IntegerField(null=True, blank=True, choices=PAST_PERFECT_AUX_CHOICES)
    past_perfect = models.CharField(max_length=255, null=True, blank=True)

    def get_past_perfect_aux(self):
        return lookup_value(Verb.PAST_PERFECT_AUX_CHOICES, self.past_perfect_aux)


class Adjective(Word):
    diminutive = models.CharField(max_length=255, null=True, blank=True)



class Sentence(models.Model):
    ref_word = models.ForeignKey(Word)
    sentence = models.CharField(max_length=10240, blank=True)


class Tag(models.Model):
    name = models.CharField(max_length=75, unique=True)

    def get_absolute_url(self):
        return '/tag/%s/' % self.name


class TagObject(models.Model):
    tag_name = models.ForeignKey(Tag)
    object_name = models.ForeignKey(Word)
    
    class Meta:
        unique_together = ("tag_name", "object_name")


class Page(models.Model):
    name = models.CharField(max_length=512, unique=True)
    content = models.CharField(max_length=10240)
    
    class Meta:
        permissions = (
            ('view_list', "Can view Page list"),
            ('view_hidden', "Can view hidden Page"),
        )
    
    def get_absolute_url(self):
        return "/page/%s/" % self.name
    
    def get_edit_url(self):
        return self.get_absolute_url() + "edit/"

src/learndutch/mainapp/forms.py
'''
Created on May 18, 2011

@author: jagadeesh
'''
from django.forms import  ModelForm, Textarea, RadioSelect, HiddenInput, Select
from models import Noun, Verb, Sentence, Tag, TagObject, Word, Page, Adjective
from django import forms

class NounForm(ModelForm):
    class Meta:
        model = Noun
        widgets = {
            'word_type': HiddenInput(),
            'info': Textarea(attrs={'cols': 50, 'rows': 5}),
            'definite_article': RadioSelect(),
            'indefinite_article': RadioSelect(),
        }

class VerbForm(ModelForm):
    class Meta:
        model = Verb
        widgets = {
            'word_type': HiddenInput(),
            'info': Textarea(attrs={'cols': 50, 'rows': 5}),
            'past_perfect_aux': RadioSelect(),
        }


class AdjectiveForm(ModelForm):
    class Meta:
        model = Adjective
        widgets = {
            'word_type': HiddenInput(),
            'info': Textarea(attrs={'cols': 50, 'rows': 5}),
        }


class WordForm(ModelForm):
    class Meta:
        model = Word
        widgets = {
            'word_type': Select(choices=Word.WORD_TYPE_CHOICES),
            'info': Textarea(attrs={'cols': 50, 'rows': 5}),
        }


class SentenceForm(forms.Form):
    ref_word_id = forms.IntegerField(widget=HiddenInput)
    sentence = forms.CharField(max_length=1024, widget=Textarea(attrs={'cols': 50, 'rows': 5}))

    def save(self):
        s = Sentence()
        s.sentence = self.cleaned_data['sentence']
        s.ref_word_id = self.cleaned_data['ref_word_id']
        s.save()
        return s


class TagForm(forms.Form):
    name = forms.CharField(max_length=75)
    object_id = forms.IntegerField(widget=HiddenInput)

    def save(self):
        t = Tag()
        t.name = self.cleaned_data['name']
        t.save()
        return t


class TagObjectForm(forms.Form):
    tag_id = forms.IntegerField()
    object_id = forms.IntegerField(widget=HiddenInput)
    
    def save(self):
        to = TagObject()
        to.tag_name_id = self.cleaned_data['tag_id']
        to.object_name_id = self.cleaned_data['object_id']
        to.save()
        return to

class PageForm(ModelForm):
    class Meta:
        model = Page
        widgets = {
            'content': Textarea(attrs={'cols': 92, 'rows': 15}),
        }

templates/add_verb.html
{% extends "master.html" %}
{% block content %}
<form action="{% url add-verb %}" method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    <div style="display:none"">{{ form.word_type }}</div>
    <p>{{ form.word.errors }} <label for="id_word">{{ form.word.label }}:</label> {{ form.word }} </p>
    <p>{{ form.meaning.errors }} <label for="id_meaning">{{ form.meaning.label }}:</label> {{ form.meaning }} </p>
    <p class="mbl bbo">{{ form.info.errors }} <label for="id_info">{{ form.info.label }}:</label> {{ form.info }} </p>
    <table class="frm-table mbl bbo">
        <tr>
            <td>&nbsp;</td>
            <td>O.T.T.</td>
            <td>O.V.T.</td>
        </tr>
        <tr>
            <td>Ik</td>
            <td>{{ form.present_1st.errors }} {{ form.present_1st }}</td>
            <td>{{ form.past_1st.errors }} {{ form.past_1st }}</td>
        </tr>
        <tr>
            <td>Jij/U</td>
            <td>{{ form.present_2nd.errors }} {{ form.present_2nd }}</td>
            <td>{{ form.past_2nd.errors }} {{ form.past_2nd }}</td>
        </tr>
        <tr>
            <td>Jij/Zij/het</td>
            <td>{{ form.present_3rd.errors }} {{ form.present_3rd }}</td>
            <td>{{ form.past_3rd.errors }} {{ form.past_3rd }}</td>
        </tr>
        <tr>
            <td>Wij <br/> Jullie/U <br/> Zij</td>
            <td> &nbsp; </td>
            <td valign="top">{{ form.past_plural.errors }} {{ form.past_plural }}</td>
        </tr>
   </table>
   <table class="frm-table mbl bbo">
        <tr>
            <td valign="top">V.T.T.</td>
            <td>{{ form.past_perfect_aux.errors }} {{ form.past_perfect_aux }}</td>
            <td valign="top">{{ form.past_perfect.errors }}  {{ form.past_perfect }}</td>
        </tr>
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/adjective.html
<p>Diminutive: {{ adjective.diminutive }}</p>

templates/login.html
{% extends "master.html" %}
{% load url from future %}
{% block content %}
<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock %}

templates/master.html
{% load site_tags %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{% block title %}Learn Dutch{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_PREFIX }}styles/main.css">
    <script type="text/javascript" src="{{ STATIC_PREFIX }}scripts/jquery-1.6.1.js"></script>
    <script type="text/javascript" src="{{ STATIC_PREFIX }}scripts/jquery.form.js"></script>
    <script type="text/javascript" src="{{ STATIC_PREFIX }}scripts/jquery.tmpl.js"></script>
    <script type="text/javascript" src="{{ STATIC_PREFIX }}scripts/word.js"></script>
</head>
<body>
<div id="site-hdr" class="bbg"><h1>Learn Dutch Easy Way</h1>
<div id="site-search">
<form id="search-frm">
    <input type="text" name="word-input" id="word-input" class="pm"></input>
    <input type="button" name="search" id="search" value="Search"></input>
</form>
</div>
{% include "components/user_tools.html" %}
</div>
<div id="site-bdy">
    <div id="menu" class="fll pll ptl">
        {% main_menu user %}
    </div>
    <div id="content" class="blg pll ptl">
        {% block content %}{% endblock %}
    </div>
    <div class="clr"></div>
</div>
<div id="site-ftr" class="btg"></div>
</body>
<script type="text/javascript">
$(document).ready(function() {
	WordSearch.init();
	SentenceForm.init();
	TagForm.init();
	WordForm.init();
});
</script>
</html>

templates/noun.html
<table class="noun-table mbl">
<tr>
    <td class="bbb">&nbsp;</td>
    <td class="bbb">singular</td>
    <td class="bbb">plural</td>
</tr>
<tr>
    <td>definite:</td>
    <td><h4><strong>{{ noun.get_singular }}</strong></h4></td>
    <td><h4>{{ noun.get_plural }}</h4></td>
</tr>
<tr>
    <td>indefinite:</td>
    <td><h4>{{ noun.get_indefinite_singular }}</h4></td>
    <td><h4>{{ noun.get_indefinite_plural }}</h4></td>
</tr>
<tr>
    <td class="bbb">diminutive:</td>
    <td class="bbb"><h4>{{ noun.get_diminutive }}</h4></td>
    <td class="bbb">&nbsp;</td>
</tr>
</table>

templates/page.html
{% extends "master.html" %}
{% block content %}
{% load site_tags %}
<div class='textile'>
    {{ object.content|textile }}
</div>
{% endblock %}

templates/page_form.html
{% extends "master.html" %}
{% block content %}
{% if object %}
<form action="{{ object.get_edit_url }}" method="post">
{% else %}
<form action="{% url add-page %}" method="post">
{% endif %}
{% csrf_token %}
    {{ form.non_field_errors }}
    <p>{{ form.name.errors }} <label for="id_name">{{ form.name.label }}:</label> {{ form.name }} </p>
    <p>{{ form.content.errors }} {{ form.content }} </p>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/tag_form.html
{% if perms.mainapp.add_tag %}
<a href="javascript:void(0);" class="action-add-tag dim-action">tag</a>
<div class="tag-frm-ctr" style="display:none;">
<div id="tag-feedback"></div>
<form id="tag-frm" action="{% url add-tag %}" method="post">{% csrf_token %}
    {{ form.object_id }}
    {{ form.name }}
</form>
</div>
{% endif %}

templates/tag_list.html
<div class="mbm">
<ul class="row-list tag-list">
    <li><span><strong>Tags:</strong></span></li>
{% for tag in tag_list %}
    <li><a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a></li>
{% endfor %}
</ul>
<div class="clr"></div>
</div>

templates/verb.html
<table class="verb-table mbl">
<tr>
    <td class="bbb">&nbsp;</td>
    <td class="bbb">O.T.T.</td>
    <td class="bbb">V.T.T</td>
</tr>
<tr>
    <td>Ik</td>
    <td><h4>{{ verb.present_1st }}</h4></td>
    <td><h4>{{ verb.past_singular }}</h4></td>
</tr>
<tr>
    <td>Jij/U</td>
    <td><h4>{{ verb.present_2nd }}</h4></td>
    <td><h4>{{ verb.past_singular }}</h4></td>
</tr>
<tr>
    <td>Hij/Zij/het</td>
    <td><h4>{{ verb.present_3rd }}</h4></td>
    <td><h4>{{ verb.past_singular }}</h4></td>
</tr>
<tr>
    <td class="bbb">Wij <br/> Jullie/U <br/> Zij</td>
    <td class="bbb" valign="top"><h4>{{ verb.word }}</h4></td>
    <td class="bbb" valign="top"><h4>{{ verb.past_plural }}</h4></td>
</tr>
<tr>
    <td class="bbb">V.T.T.</td>
    <td class="bbb"><h4>{{ verb.get_past_perfect_aux }}</h4></td>
    <td class="bbb"><h4>{{ verb.past_perfect }}</h4></td>
</tr>
</table>

templates/verb_form.html
{% extends "master.html" %}
{% block content %}
{% if object %}
<form action="{{ object.get_edit_url }}" method="post" enctype="multipart/form-data">
{% else %}
<form action="{% url add-verb %}" method="post" enctype="multipart/form-data">
{% endif %}
{% csrf_token %}
    {% include "word_form_common.html" with form=form %}

    <p>O.T.T.</p>
    <p>{{ form.present_1st.errors }} <label for="id_present_1st">ik</label> {{ form.present_1st }} </p>
    <p>{{ form.present_2nd.errors }} <label for="id_present_2nd">jij u</label> {{ form.present_2nd }} </p>
    <p class="mbl bbo">{{ form.present_3rd.errors }} <label for="id_present_3rd">hij zij het</label> {{ form.present_3rd }} </p>

    <p>O.V.T.</p>
    <p>{{ form.past_singular.errors }} <label for="id_past_singular">ik jij hij zij het</label> {{ form.past_singular }} </p>
    <p class="mbl bbo">{{ form.past_plural.errors }} <label for="id_past_plural">wij/we jullie/u zij</label> {{ form.past_plural }} </p>

    <table class="frm-table mbl bbo">
        <tr>
            <td valign="top">V.T.T.</td>
            <td>{{ form.past_perfect_aux.errors }} {{ form.past_perfect_aux }}</td>
            <td valign="top">{{ form.past_perfect.errors }}  {{ form.past_perfect }}</td>
        </tr>
    </table>

    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/word.html
{% extends "master.html" %}
{% block content %}
<div class="mll">
    <div class="mbm"><h3><strong>{{ object.get_word }}</strong></h3> {%if perms.mainapp.edit_word %} <a href="{{ object.get_edit_url }}" class="dim-action">edit</a>{% endif %} {{ object.get_meaning }} </div>
    {% if object.image %}
    <div>
        <img src="{{ object.image.url }}" >
    </div>
    {% endif %}
    {% include "tag_list.html" with tag_list=tag_list %}
    {% include "tag_form.html" with form=tag_form %}
    {% if object.info %}
        <p>{{ object.info }}</p>
    {% endif %}
    {% if object.is_noun %}
        {% include "noun.html" with noun=object.noun %}
    {% endif %}
    {% if object.is_verb %}
        {% include "verb.html" with verb=object.verb %}
    {% endif %}
    {% if object.is_adjective %}
        {% include "adjective.html" with adjective=object.adjective %}
    {% endif %}
    <div class="mbm"><strong>Examples:</strong></div>
    {% include "sentence_list.html" with sentence_list=sentence_list %}
</div>
    {% include "sentence_form.html" with form=setence_form %}
{% endblock %}

templates/word_form_common.html
{{ form.non_field_errors }}
<div style="display:none"">{{ form.word_type }}</div>
<p>{{ form.word.errors }} <label for="id_word">{{ form.word.label }}:</label> {{ form.word }} </p>
<p>{{ form.meaning.errors }} <label for="id_meaning">Meaning:</label> {{ form.meaning }} </p>
<p>{{ form.info.errors }} <label for="id_info">{{ form.info.label }}:</label> {{ form.info }} </p>
<p>{{ form.image.errors }} <label for="id_image">{{ form.image.label }}:</label> {{ form.image }} </p>
<p class="mbl bbo">{{ form.audio.errors }} <label for="id_audio">{{ form.audio.label }}:</label> {{ form.audio }} </p>

templates/word_list.html
{% extends "master.html" %}
{% block content %}
<ul class='item-list'>
    {% for word in object_list %}
        <li><h4><a href="{{ word.get_absolute_url }}">{{ word.word }}</a></h4> (<a href="{{ word.get_edit_url }}" class="dim-action">edit</a>) {{ word.get_meaning }}</li>
    {% endfor %}
</ul>
{% include "components/default_pager.html" %}
{% endblock %}